name: Lint

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, auto_merge_enabled]

concurrency:
  group: lint-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/checkout@v4
      - run: npm i
      - run: npm run lint