name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    environment: npm
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: 24
        registry-url: https://registry.npmjs.org/
    - name: run tests
      run: |
        npm i -g @sap/cds-dk
        npm i
        npm run lint
        npm run test
    - name: Get Version
      id: get-version
      run: |
        echo "version=$(npm pkg get version | tr -d '"')" >> $GITHUB_OUTPUT
    - name: parse changelog
      id: parse-changelog
      uses: schwma/parse-changelog-action@1c2b2005ccf594cc3a45d33c10af4ab924d3a1c5 # v1.2.0
      with:
        version: '${{ steps.get-version.outputs.version }}'
    - name: create a GitHub release
      uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
      with:
        tag: 'v${{ steps.get-version.outputs.version }}'
        body: '${{ steps.parse-changelog.outputs.body }}'
    - run: npm publish --access public --provenance
