name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    environment: npm
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
    - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
      with:
        node-version: 24
        registry-url: https://registry.npmjs.org/
    - name: run tests
      run: |
        npm i -g @sap/cds-dk
        npm i
        npm run lint
        npm run test
    - name: Get Version
      id: get-version
      run: |
        echo "version=$(npm pkg get version | tr -d '"')" >> $GITHUB_OUTPUT
    - name: parse changelog
      id: parse-changelog
      uses: schwma/parse-changelog-action@69a9f9ab4cf2f2e736108ab41396fc3c55f65e40 # v1.0.0
      with:
        version: '${{ steps.get-version.outputs.version }}'
    - name: create a GitHub release
      uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
      with:
        tag: 'v${{ steps.get-version.outputs.version }}'
        body: '${{ steps.parse-changelog.outputs.body }}'
    - run: npm publish --access public --provenance
